name: "init"
description: "initialize nix"
runs:
  using: "composite"
  steps:
    - uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
      with:
        egress-policy: audit

    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - uses: DeterminateSystems/nix-installer-action@786fff0690178f1234e4e1fe9b536e94f5433196 # v20
      with:
        extra-conf: |
          extra-substituters = https://trevnur.cachix.org
          extra-trusted-public-keys = trevnur.cachix.org-1:hBd15IdszwT52aOxdKs5vNTbq36emvEeGqpb25Bkq6o=

    - uses: spotdemo4/nix-simple-cache-action@be74283a8cc4c00b53a7b1dbdfbd9679bbdf0629 # v1.4.13
