name: check

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        id: init
        uses: spotdemo4/nix-init@653c485759755505036c9e4b09b86b1f6a6ae511 # v1.8.7

      - name: Run checks
        if: ${{ steps.init.outputs.duplicate != 'true' }}
        run: nix flake check
