name: check

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@7b3c73a036788c813cef96f63cd32e622ba616f0 # v1.61.0

      - name: Check
        run: nix flake check
